name: Download DB-IP's file. 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Downloader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '114'
          
      - name: Use Chrome Path and Version
        run: |
          echo "Chrome path is ${{ steps.setup-chrome.outputs.chrome-path }}"
          echo "Chrome version is ${{ steps.setup-chrome.outputs.chrome-version }}"
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROME_VERSION: ${{ steps.setup-chrome.outputs.chrome-version }}
          
      - name: Build and Run downloader.go
        run: |
          go run downloader.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloaded-files
          path: |
            ./*.mmdb
            ./*.log
