name: Download DB-IP's file. 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Downloader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.9.1
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '114'

      - name: Build and Run downloader.go
        run: |
          go run downloader.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloaded-files
          path: |
            ./*.mmdb
            ./*.log
